a = float (input ("Введіть а = "))
b = float (input ("Введіть b = "))
print ("Сума", (a + b))
print ("Різниця", (a - b))
print ("Множення", (a * b))
print ("Ділення", (a / b))
print ("Піднесення до степеня", (a ** b))